# Generated by Django 5.2.5 on 2025-08-09 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantidade_total', models.PositiveIntegerField(verbose_name='Quantidade Total em Estoque')),
                ('quantidade_disponivel', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA', 'Saída para Escola'), ('ENTRADA', 'Entrada no Estoque')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.escola', verbose_name='Escola')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item', verbose_name='Item')),
            ],
        ),
    ]
